window.PREP_SEARCH_INDEX = [
  {
    title: "PrepSphere Home",
    topic: "Dashboard",
    url: "index.html",
    keywords: "home dashboard topics interview universe 3d navigation overview about",
  },
  {
    title: "DBMS",
    topic: "DBMS",
    url: "01-DBMS.html",
    keywords: "database management system acid normalization denormalization keys indexing transactions locks cap theorem sql nosql",
  },
  {
    title: "ACID Properties",
    topic: "DBMS",
    url: "01-DBMS.html#acid",
    keywords: "atomicity consistency isolation durability transaction properties rollback commit",
  },
  {
    title: "Normalization",
    topic: "DBMS",
    url: "01-DBMS.html#normalization",
    keywords: "1nf 2nf 3nf bcnf redundancy dependency schema design",
  },
  {
    title: "Indexing",
    topic: "DBMS",
    url: "01-DBMS.html#indexing",
    keywords: "btree hash clustered non clustered composite leftmost prefix query performance",
  },
  {
    title: "Transactions and Locks",
    topic: "DBMS",
    url: "01-DBMS.html#transactions",
    keywords: "commit rollback concurrency locking shared exclusive deadlock",
  },
  {
    title: "Isolation Levels",
    topic: "DBMS",
    url: "01-DBMS.html#isolation",
    keywords: "read uncommitted committed repeatable serializable dirty read phantom non repeatable",
  },
  {
    title: "CAP Theorem",
    topic: "DBMS",
    url: "01-DBMS.html#cap",
    keywords: "consistency availability partition tolerance distributed systems cassandra mongodb hbase",
  },
  {
    title: "SQL vs NoSQL",
    topic: "DBMS",
    url: "01-DBMS.html#sqlnosql",
    keywords: "relational non relational document key value graph column database choice",
  },
  {
    title: "Object-Oriented Programming",
    topic: "OOP",
    url: "02-OOPs.html",
    keywords: "oops object oriented class object inheritance polymorphism abstraction encapsulation",
  },
  {
    title: "Four Pillars",
    topic: "OOP",
    url: "02-OOPs.html#pillars",
    keywords: "encapsulation abstraction inheritance polymorphism pillars",
  },
  {
    title: "SOLID Principles",
    topic: "OOP",
    url: "02-OOPs.html#solid",
    keywords: "single responsibility open closed liskov interface segregation dependency inversion",
  },
  {
    title: "Diamond Problem",
    topic: "OOP",
    url: "02-OOPs.html#diamond",
    keywords: "multiple inheritance ambiguity virtual inheritance base class",
  },
  {
    title: "Computer Networks",
    topic: "Networks",
    url: "03-Computer-Networks.html",
    keywords: "networking osi tcp udp ip http dns tls load balancer cdn rest websocket",
  },
  {
    title: "OSI Model",
    topic: "Networks",
    url: "03-Computer-Networks.html#osi",
    keywords: "layers physical data link network transport session presentation application",
  },
  {
    title: "TCP vs UDP",
    topic: "Networks",
    url: "03-Computer-Networks.html#tcp-udp",
    keywords: "reliable connection handshake congestion control datagram packet",
  },
  {
    title: "HTTP and HTTPS",
    topic: "Networks",
    url: "03-Computer-Networks.html#http",
    keywords: "request response methods status codes tls ssl secure web",
  },
  {
    title: "DNS",
    topic: "Networks",
    url: "03-Computer-Networks.html#dns",
    keywords: "domain name resolution recursive resolver root tld authoritative cache",
  },
  {
    title: "Operating Systems",
    topic: "OS",
    url: "04-Operating-System.html",
    keywords: "operating system process thread memory scheduling deadlock paging virtual memory",
  },
  {
    title: "Process vs Thread",
    topic: "OS",
    url: "04-Operating-System.html#proc-thread",
    keywords: "process thread context switch shared memory pcb tcb",
  },
  {
    title: "Scheduling",
    topic: "OS",
    url: "04-Operating-System.html#scheduling",
    keywords: "fcfs sjf round robin priority cpu scheduler turnaround waiting time",
  },
  {
    title: "Deadlock",
    topic: "OS",
    url: "04-Operating-System.html#deadlock",
    keywords: "mutual exclusion hold wait no preemption circular wait prevention avoidance banker",
  },
  {
    title: "Virtual Memory",
    topic: "OS",
    url: "04-Operating-System.html#vmem",
    keywords: "paging segmentation page fault tlb demand paging swap",
  },
  {
    title: "C++ Core",
    topic: "C++",
    url: "05-Language-Core-CPP.html",
    keywords: "cpp c++ pointers references oop stl templates memory const virtual",
  },
  {
    title: "Java Core",
    topic: "Java",
    url: "05-Language-Core-Java.html",
    keywords: "java jvm jre jdk oops collections exceptions threads gc",
  },
  {
    title: "Python Core",
    topic: "Python",
    url: "05-Language-Core-Python.html",
    keywords: "python list tuple dict set generator decorator oop threading gil",
  },
  {
    title: "Puzzles",
    topic: "Puzzles",
    url: "06-Puzzles.html",
    keywords: "logic puzzle reasoning brain teaser probability clock coins hats",
  },
  {
    title: "Linux",
    topic: "Linux",
    url: "07-Linux.html",
    keywords: "linux commands shell process permissions grep find awk sed networking",
  },
  {
    title: "Git",
    topic: "Git",
    url: "08-Git.html",
    keywords: "git version control commit branch merge rebase stash reset revert cherry pick",
  },
  {
    title: "SQL",
    topic: "SQL",
    url: "09-SQL.html",
    keywords: "sql query join group by having subquery window function index transaction",
  },
  {
    title: "Joins",
    topic: "SQL",
    url: "09-SQL.html#joins",
    keywords: "inner left right full outer cross self join",
  },
  {
    title: "Window Functions",
    topic: "SQL",
    url: "09-SQL.html#nth-salary",
    keywords: "row_number rank dense_rank lag lead partition over",
  },
  {
    title: "Projects and Behavioral",
    topic: "Behavioral",
    url: "10-Projects-Behavioral.html",
    keywords: "projects behavioral star method leadership conflict ownership design tradeoff",
  },
  {
    title: "STAR Method",
    topic: "Behavioral",
    url: "10-Projects-Behavioral.html",
    keywords: "situation task action result behavioral answer structure",
  },
  {
    title: "System Design Stories",
    topic: "Behavioral",
    url: "10-Projects-Behavioral.html#architecture",
    keywords: "architecture scale performance caching database queue tradeoffs",
  },
];
