window.PREP_SEARCH_INDEX = [

  // ──────────────── HOME ────────────────
  {
    title: "PrepSphere Home",
    topic: "Home",
    chapter: "Home",
    url: "index.html",
    keywords: "home dashboard topics interview universe 3d navigation overview about prepsphere",
  },

  // ──────────────── DBMS ────────────────
  {
    title: "DBMS — Database Management System",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html",
    keywords: "database management system dbms rdbms relational sql nosql schema table query",
  },
  {
    title: "ACID Properties",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#acid",
    keywords: "acid atomicity consistency isolation durability transaction properties rollback commit WAL undo log",
  },
  {
    title: "Normalization — 1NF 2NF 3NF BCNF",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#normalization",
    keywords: "normalization 1nf 2nf 3nf bcnf normal form redundancy anomaly functional dependency decomposition schema design",
  },
  {
    title: "Denormalization",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#denormalization",
    keywords: "denormalization performance optimization redundant data read speed trade off",
  },
  {
    title: "Primary Key vs Foreign Key",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#keys",
    keywords: "primary key foreign key candidate super composite unique referential integrity constraint",
  },
  {
    title: "Indexing in Databases",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#indexing",
    keywords: "index indexing btree hash clustered non clustered composite covering leftmost prefix query performance scan",
  },
  {
    title: "Clustered vs Non-Clustered Index",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#clustered",
    keywords: "clustered non clustered index leaf page sorting physical order logical order",
  },
  {
    title: "B+ Trees",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#btree",
    keywords: "b+ tree btree balanced tree node leaf internal structure range query",
  },
  {
    title: "Joins — All Types",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#joins",
    keywords: "join inner left right full outer cross self natural equi join cartesian product",
  },
  {
    title: "Transactions",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#transactions",
    keywords: "transaction commit rollback begin acid concurrent schedule serializable recoverable",
  },
  {
    title: "Locks in DBMS",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#locks",
    keywords: "lock shared exclusive read write optimistic pessimistic two phase locking 2pl deadlock",
  },
  {
    title: "Deadlock",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#deadlock",
    keywords: "deadlock cycle wait prevention detection recovery wait die wound wait",
  },
  {
    title: "Isolation Levels",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#isolation",
    keywords: "isolation level read uncommitted committed repeatable serializable dirty read phantom non repeatable mvcc",
  },
  {
    title: "CAP Theorem",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#cap",
    keywords: "cap theorem consistency availability partition tolerance distributed systems cassandra mongodb hbase eventual",
  },
  {
    title: "Sharding",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#sharding",
    keywords: "sharding partition horizontal vertical shard key distribution scaling database",
  },
  {
    title: "SQL vs NoSQL",
    topic: "DBMS",
    chapter: "DBMS",
    url: "01-DBMS.html#sqlnosql",
    keywords: "sql nosql relational non relational document key value graph column database choice when to use mongodb postgres",
  },

  // ──────────────── OOPs ────────────────
  {
    title: "OOP — Object-Oriented Programming",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html",
    keywords: "oops object oriented programming class object instance encapsulation abstraction inheritance polymorphism",
  },
  {
    title: "Four Pillars of OOP",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#pillars",
    keywords: "pillars encapsulation abstraction inheritance polymorphism data hiding interface extend override",
  },
  {
    title: "Runtime vs Compile-Time Polymorphism",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#polymorphism",
    keywords: "polymorphism runtime compile time dynamic static early late binding virtual function overloading overriding",
  },
  {
    title: "Overloading vs Overriding",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#overload-override",
    keywords: "overloading overriding method same name different parameters signature return type",
  },
  {
    title: "Interface vs Abstract Class",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#interface-abstract",
    keywords: "interface abstract class contract implementation multiple inheritance default method",
  },
  {
    title: "Association, Aggregation, Composition",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#relationships",
    keywords: "association aggregation composition has-a relationship ownership lifecycle dependency weak strong",
  },
  {
    title: "SOLID Principles",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#solid",
    keywords: "solid single responsibility open closed liskov substitution interface segregation dependency inversion principle",
  },
  {
    title: "Constructor Chaining",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#constructor",
    keywords: "constructor chaining this super initialization overload default parameterized copy",
  },
  {
    title: "Deep vs Shallow Copy",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#cloning",
    keywords: "deep copy shallow clone reference object duplication nested independent",
  },
  {
    title: "Static vs Instance Members",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#static",
    keywords: "static instance class object member variable method shared per object",
  },
  {
    title: "Access Modifiers",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#access",
    keywords: "access modifier public private protected default package visibility scope",
  },
  {
    title: "Diamond Problem",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#diamond",
    keywords: "diamond problem multiple inheritance ambiguity virtual base class mixin trait",
  },
  {
    title: "Dependency Injection",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#di",
    keywords: "dependency injection inversion of control ioc loose coupling constructor setter interface",
  },
  {
    title: "Cohesion vs Coupling",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#cohesion",
    keywords: "cohesion coupling high low module responsibility dependency tight loose",
  },
  {
    title: "Immutable Objects",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#immutable",
    keywords: "immutable object thread safe final string unmodifiable state defensive copy",
  },
  {
    title: "Design Patterns",
    topic: "OOP",
    chapter: "OOP",
    url: "02-OOPs.html#patterns",
    keywords: "design pattern singleton factory observer strategy decorator adapter facade proxy builder iterator",
  },

  // ──────────────── COMPUTER NETWORKS ────────────────
  {
    title: "Computer Networks",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html",
    keywords: "computer networks networking osi tcp udp ip http https dns tls ssl load balancer cdn rest websocket reverse proxy",
  },
  {
    title: "TCP vs UDP",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#tcp-udp",
    keywords: "tcp udp transmission control user datagram reliable connection oriented handshake congestion flow control stream",
  },
  {
    title: "OSI Model — 7 Layers",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#osi",
    keywords: "osi model open systems interconnection 7 layers physical data link network transport session presentation application",
  },
  {
    title: "TCP/IP Model",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#tcpip",
    keywords: "tcp ip model internet protocol stack 4 layers network access internet transport application",
  },
  {
    title: "Three-Way Handshake",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#handshake",
    keywords: "three way handshake syn syn-ack ack connection establishment tcp",
  },
  {
    title: "Four-Way Connection Termination",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#termination",
    keywords: "four way termination fin ack close wait time wait connection close teardown",
  },
  {
    title: "HTTP vs HTTPS",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#http",
    keywords: "http https hypertext transfer protocol secure tls ssl encryption port 80 443 request response methods status codes",
  },
  {
    title: "DNS — Domain Name System",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#dns",
    keywords: "dns domain name system resolution recursive resolver root tld authoritative cache record a aaa cname mx ns",
  },
  {
    title: "Load Balancer",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#lb",
    keywords: "load balancer load balancing round robin least connection ip hash health check upstream nginx haproxy",
  },
  {
    title: "Reverse Proxy",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#rp",
    keywords: "reverse proxy forward proxy server client nginx apache gateway filter",
  },
  {
    title: "SSL/TLS Encryption",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#tls",
    keywords: "ssl tls certificate handshake encryption asymmetric symmetric public private key x509 ca authority",
  },
  {
    title: "Cookies vs Sessions",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#cookies",
    keywords: "cookie session state management client server local storage session storage tracking",
  },
  {
    title: "REST APIs",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#rest",
    keywords: "rest api representational state transfer get post put delete patch endpoint resource crud stateless",
  },
  {
    title: "WebSocket — Real-Time Communication",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#ws",
    keywords: "websocket ws wss real time full duplex persistent connection socket io chat streaming bidirectional",
  },
  {
    title: "CDN — Content Delivery Network",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#cdn",
    keywords: "cdn content delivery network edge server cache latency cloudflare akamai static asset distribution",
  },
  {
    title: "How Browser Opens Google.com",
    topic: "Networks",
    chapter: "Computer Networks",
    url: "03-Computer-Networks.html#google",
    keywords: "browser google url dns tcp tls http request response render parse html css js dom",
  },

  // ──────────────── OPERATING SYSTEM ────────────────
  {
    title: "Operating System",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html",
    keywords: "operating system os process thread memory scheduling deadlock paging virtual kernel user space",
  },
  {
    title: "Process vs Thread",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#proc-thread",
    keywords: "process thread pcb tcb context switch shared memory address space lightweight heavyweight",
  },
  {
    title: "Context Switching",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#ctx-switch",
    keywords: "context switch overhead register stack state save restore mode bit kernel user",
  },
  {
    title: "Multithreading",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#multithreading",
    keywords: "multithreading concurrent parallel thread pool user kernel level benefits problems",
  },
  {
    title: "Scheduling Algorithms",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#scheduling",
    keywords: "scheduling fcfs sjf round robin priority preemptive non preemptive turnaround waiting response time cpu",
  },
  {
    title: "Deadlock in OS",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#deadlock",
    keywords: "deadlock mutual exclusion hold wait no preemption circular wait prevention avoidance banker algorithm detection recovery",
  },
  {
    title: "Starvation",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#starvation",
    keywords: "starvation aging fairness priority indefinite blocking low priority process",
  },
  {
    title: "Race Condition",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#race",
    keywords: "race condition critical section concurrent shared variable synchronization data inconsistency",
  },
  {
    title: "Mutex Lock",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#mutex",
    keywords: "mutex mutual exclusion lock unlock binary semaphore ownership",
  },
  {
    title: "Semaphore",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#semaphore",
    keywords: "semaphore counting binary wait signal pv operation resource management",
  },
  {
    title: "Paging",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#paging",
    keywords: "paging page frame table fault demand pagination replacement lru fifo optimal",
  },
  {
    title: "Segmentation",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#segmentation",
    keywords: "segmentation segment code data stack heap logical address offset",
  },
  {
    title: "Virtual Memory",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#vmem",
    keywords: "virtual memory paging swap demand page fault tlb mmu address translation",
  },
  {
    title: "Heap vs Stack Memory",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#heap-stack",
    keywords: "heap stack memory allocation dynamic static lifo fifo buffer overflow",
  },
  {
    title: "Memory Allocation",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#mem-alloc",
    keywords: "memory allocation first fit best worst buddy system fragmentation internal external",
  },
  {
    title: "Garbage Collection",
    topic: "OS",
    chapter: "Operating System",
    url: "04-Operating-System.html#gc",
    keywords: "garbage collection gc mark sweep compact generational reference counting java python automatic memory management",
  },

  // ──────────────── C++ ────────────────
  {
    title: "C++ Language Core",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html",
    keywords: "cpp c++ language core pointers references oop stl templates memory const virtual",
  },
  {
    title: "Stack vs Heap Memory in C++",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#stack-heap",
    keywords: "stack heap memory allocation free store new delete automatic dynamic scope lifetime",
  },
  {
    title: "Compile-Time vs Runtime Polymorphism",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#polymorphism",
    keywords: "compile time runtime polymorphism virtual function vtable override overload template",
  },
  {
    title: "C++ Compilation Process",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#compilation",
    keywords: "compilation preprocess compile assemble link object file executable header translation unit",
  },
  {
    title: "Virtual Functions & VTable",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#vtable",
    keywords: "virtual function vtable vptr pointer dynamic dispatch override pure abstract base",
  },
  {
    title: "Shallow vs Deep Copy in C++",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#copy-depth",
    keywords: "shallow deep copy assignment operator constructor clone duplicate pointer ownership",
  },
  {
    title: "Copy vs Move Constructor",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#copy-move",
    keywords: "copy move constructor rvalue reference std::move steal resource efficient transfer ownership",
  },
  {
    title: "Smart Pointers — unique shared weak",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#smart-ptr",
    keywords: "smart pointer unique_ptr shared_ptr weak_ptr raii automatic delete memory leak ownership reference counting",
  },
  {
    title: "Process vs Thread in C++",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#proc-thread",
    keywords: "process thread std::thread mutex concurrent parallel multiprocessing",
  },
  {
    title: "Memory Leak & Segfault in C++",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#mem-issues",
    keywords: "memory leak segfault segmentation fault valgrind undefined behavior dangling pointer double free",
  },
  {
    title: "malloc/free vs new/delete",
    topic: "C++",
    chapter: "C++",
    url: "05-Language-Core-CPP.html#malloc-new",
    keywords: "malloc free new delete calloc realloc heap allocation constructor destructor",
  },

  // ──────────────── JAVA ────────────────
  {
    title: "Java Language Core",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html",
    keywords: "java jvm jre jdk oop collections exceptions multithreading garbage collection memory spring",
  },
  {
    title: "JDK, JRE, JVM — The Holy Trinity",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c1",
    keywords: "jdk jre jvm java development kit runtime environment virtual machine bytecode compiler",
  },
  {
    title: "How Java Achieves Platform Independence",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c2",
    keywords: "platform independence write once run anywhere bytecode jvm portable cross compile",
  },
  {
    title: "Heap vs Stack Memory in JVM",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c3",
    keywords: "heap stack jvm memory young generation old eden survivor garbage metaspace",
  },
  {
    title: "Garbage Collection in Java",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c4",
    keywords: "garbage collection gc mark sweep compact g1 zgc serial parallel cms jvm automatic memory",
  },
  {
    title: "== vs equals() in Java",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c5",
    keywords: "equals hashcode reference comparison value object string literal pool identity",
  },
  {
    title: "HashMap vs ConcurrentHashMap",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c6",
    keywords: "hashmap concurrenthashmap thread safe synchronization bucket hash table map",
  },
  {
    title: "Process vs Thread in Java",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c7",
    keywords: "process thread runnable callable executor threadpool concurrent",
  },
  {
    title: "Synchronization and Deadlock in Java",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c8",
    keywords: "synchronization deadlock synchronized lock wait notify race condition thread safe",
  },
  {
    title: "What Happens When a Java Program Runs",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c9",
    keywords: "java program execution compile bytecode classloader jvm verify execute jit main method",
  },
  {
    title: "String vs StringBuilder vs StringBuffer",
    topic: "Java",
    chapter: "Java",
    url: "05-Language-Core-Java.html#c10",
    keywords: "string stringbuilder stringbuffer immutable mutable thread safe performance concat pool",
  },

  // ──────────────── PYTHON ────────────────
  {
    title: "Python Language Core",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html",
    keywords: "python language core list tuple dict set generator decorator oop gil threading memory",
  },
  {
    title: "GIL — Global Interpreter Lock",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q1",
    keywords: "gil global interpreter lock python thread cpu bound single multiprocessing bypass",
  },
  {
    title: "Multithreading vs Multiprocessing in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q2",
    keywords: "multithreading multiprocessing concurrent parallel io cpu bound gil process pool",
  },
  {
    title: "Mutable vs Immutable Objects in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q3",
    keywords: "mutable immutable list tuple dict set string int frozen hashable",
  },
  {
    title: "is vs == in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q4",
    keywords: "is equals identity value comparison object reference None singleton",
  },
  {
    title: "Deep Copy vs Shallow Copy in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q5",
    keywords: "deep shallow copy deepcopy clone nested list dict reference independent",
  },
  {
    title: "Python Memory Management",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q6",
    keywords: "memory management reference counting garbage collector gc cyclic generation heap pymalloc",
  },
  {
    title: "How Python Code Executes Internally",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q7",
    keywords: "python execution bytecode compilation pyc interpreter cpython ast token parse",
  },
  {
    title: "List vs Tuple in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q8",
    keywords: "list tuple array sequence ordered mutable immutable performance memory",
  },
  {
    title: "Generators & Why They Are Memory Efficient",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q9",
    keywords: "generator yield lazy evaluation iterator fibonacci stream memory efficient infinite",
  },
  {
    title: "Interpreter vs Compiler in Python",
    topic: "Python",
    chapter: "Python",
    url: "05-Language-Core-Python.html#q10",
    keywords: "interpreter compiler bytecode jit cpython pypy just in time ahead of time",
  },

  // ──────────────── PUZZLES ────────────────
  {
    title: "Interview Puzzles & Brain Teasers",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html",
    keywords: "puzzle brain teaser logic reasoning probability interview aptitude riddle",
  },
  {
    title: "25 Horses Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#horses",
    keywords: "25 horses race 5 track top fastest minimum races puzzle optimization",
  },
  {
    title: "8 Ball Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#8ball",
    keywords: "8 ball heavier lighter balance weighing scale minimum weight puzzle",
  },
  {
    title: "Bridge and Torch",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#bridge",
    keywords: "bridge torch crossing night minimum time puzzle speed strategy",
  },
  {
    title: "Water Jug Problem",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#jug",
    keywords: "water jug measure liter gallon transfer puzzle gcd",
  },
  {
    title: "100 Prisoners Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#prisoners",
    keywords: "100 prisoners light bulb strategy days probability puzzle",
  },
  {
    title: "Egg Dropping Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#egg",
    keywords: "egg dropping floor minimum attempts critical dynamic programming puzzle",
  },
  {
    title: "Coin Flip Problems",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#coin",
    keywords: "coin flip biased fair probability heads tails random puzzle",
  },
  {
    title: "Poisoned Bottle Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#poison",
    keywords: "poisoned bottle wine prisoner test binary representation puzzle",
  },
  {
    title: "Pirate Gold Division",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#pirate",
    keywords: "pirate gold coin division proposal vote strategy game theory puzzle",
  },
  {
    title: "Clock Angle Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#clock",
    keywords: "clock angle hour hand minute degree overlap formula puzzle",
  },
  {
    title: "Train Crossing Problem",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#train",
    keywords: "train crossing bridge tunnel speed time length relative puzzle",
  },
  {
    title: "River Crossing Puzzle",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#river",
    keywords: "river crossing boat farmer wolf goat cabbage fox chicken puzzle",
  },
  {
    title: "Dice Probability Questions",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#dice",
    keywords: "dice probability sum expected value roll fair six sided puzzle",
  },
  {
    title: "Monty Hall Problem",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#monty",
    keywords: "monty hall problem door switch probability conditional bayes puzzle",
  },
  {
    title: "Logic Deduction Puzzles",
    topic: "Puzzles",
    chapter: "Puzzles",
    url: "06-Puzzles.html#logic",
    keywords: "logic deduction reasoning critical thinking puzzle statement truth",
  },

  // ──────────────── LINUX ────────────────
  {
    title: "Linux — System Administration",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html",
    keywords: "linux commands shell terminal process permissions file system grep find awk sed networking ssh",
  },
  {
    title: "What Happens When You Type a Command",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q1",
    keywords: "command terminal shell bash parse path execute fork exec process",
  },
  {
    title: "Process vs Thread in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q2",
    keywords: "process thread linux task_struct clone pid tid kernel scheduling",
  },
  {
    title: "Zombie Process",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q3",
    keywords: "zombie process defunct wait pid SIGCHLD orphan reap exit status",
  },
  {
    title: "Daemon Process",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q4",
    keywords: "daemon process background service init systemd fork nohup detach",
  },
  {
    title: "Hard Link vs Soft Link (Symlink)",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q5",
    keywords: "hard link soft symlink symbolic inode reference pointer filesystem",
  },
  {
    title: "Inode in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q6",
    keywords: "inode index node metadata file size permissions data block pointer",
  },
  {
    title: "chmod 755 Explained",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q7",
    keywords: "chmod permission 755 644 rwx read write execute owner group others octal",
  },
  {
    title: "kill vs kill -9",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q8",
    keywords: "kill signal sigterm sigkill 9 15 graceful force process terminate",
  },
  {
    title: "grep vs find vs locate",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q9",
    keywords: "grep find locate search pattern regex file content name database updatedb",
  },
  {
    title: "> vs >> Redirect in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q10",
    keywords: "redirect output append overwrite stdout stderr pipe tee",
  },
  {
    title: "Pipe | in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q11",
    keywords: "pipe stdout stdin chain command filter stream",
  },
  {
    title: "Swap Memory in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q12",
    keywords: "swap memory disk virtual page ram full overflow partition",
  },
  {
    title: "What Happens When RAM Gets Full",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q13",
    keywords: "ram full oom out of memory killer swap page reclaim cache",
  },
  {
    title: "TCP vs UDP in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q14",
    keywords: "tcp udp netstat ss connection protocol reliable datagram",
  },
  {
    title: "HTTP vs HTTPS in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q15",
    keywords: "http https ssl tls certificate curl wget secure port",
  },
  {
    title: "SSH — Secure Shell",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q16",
    keywords: "ssh secure shell remote login key authentication port 22 scp rsa",
  },
  {
    title: "Cron Jobs",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q17",
    keywords: "cron job crontab schedule periodic task interval minute hour daily",
  },
  {
    title: "Environment Variables & PATH",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q18",
    keywords: "environment variable path export .bashrc .profile echo $PATH",
  },
  {
    title: "fork() and exec() in Linux",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q19",
    keywords: "fork exec system call child process copy on write spawn create replace",
  },
  {
    title: "Production Server Down — How to Debug",
    topic: "Linux",
    chapter: "Linux",
    url: "07-Linux.html#q20",
    keywords: "production server down debug troubleshooting top htop df free logs journalctl dmesg",
  },

  // ──────────────── GIT ────────────────
  {
    title: "Git — Version Control",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html",
    keywords: "git version control repository commit branch merge rebase stash reset revert pull push clone",
  },
  {
    title: "What is Git?",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q1",
    keywords: "git what is version control distributed tracking history snapshot",
  },
  {
    title: "Git vs GitHub",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q2",
    keywords: "git github difference local remote hosting platform collaboration",
  },
  {
    title: "What is a Repository?",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q3",
    keywords: "repository repo working directory staging index .git folder history",
  },
  {
    title: "git pull vs git fetch",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q4",
    keywords: "pull fetch remote merge download update local difference",
  },
  {
    title: "git merge vs git rebase",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q5",
    keywords: "merge rebase fast forward squash conflict linear history commit",
  },
  {
    title: "Branch in Git",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q6",
    keywords: "branch feature create checkout switch pointer head lightweight",
  },
  {
    title: "Pull Requests (PR)",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q7",
    keywords: "pull request pr merge review code collaboration branch github",
  },
  {
    title: "Git Stash",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q8",
    keywords: "stash save temporary shelf uncommitted changes pop apply list",
  },
  {
    title: "git reset vs git revert",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q9",
    keywords: "reset revert soft mixed hard undo commit history pointer",
  },
  {
    title: "Merge Conflict",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q10",
    keywords: "merge conflict resolve <<<< ==== >>>> same file line change",
  },
  {
    title: "Resolving Merge Conflicts",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q11",
    keywords: "resolve merge conflict manual edit accept ours theirs strategy tool",
  },
  {
    title: "Local vs Remote Repository",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q12",
    keywords: "local remote origin upstream downstream push fetch tracking",
  },
  {
    title: ".gitignore File",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q13",
    keywords: "gitignore ignore exclude file pattern node_modules env build log",
  },
  {
    title: "git clone vs git fork",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q14",
    keywords: "clone fork copy repository local server github own account",
  },
  {
    title: "HEAD in Git",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q15",
    keywords: "head pointer current branch commit reference symbolic detached",
  },
  {
    title: "git add . vs git add <file>",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q16",
    keywords: "git add stage all file specific dot staging area index",
  },
  {
    title: "Detached HEAD State",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q17",
    keywords: "detached head commit checkout tag history not branch",
  },
  {
    title: "Git Workflow in Teams",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q18",
    keywords: "workflow team gitflow feature branch trunk based release collaborate",
  },
  {
    title: "How to Undo a Commit",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q19",
    keywords: "undo commit reset revert amend soft hard last pushed unpushed",
  },
  {
    title: "Code Works Locally but Fails After Merge",
    topic: "Git",
    chapter: "Git",
    url: "08-Git.html#q20",
    keywords: "local works merge fails deploy debug ci cd environment dependency difference",
  },

  // ──────────────── SQL ────────────────
  {
    title: "SQL — Structured Query Language",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html",
    keywords: "sql query select insert update delete join group by having where subquery window function index transaction",
  },
  {
    title: "Nth Highest Salary",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#nth-salary",
    keywords: "nth highest salary rank dense_rank row_number limit offset subquery top",
  },
  {
    title: "2nd Highest Salary",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#2nd-salary",
    keywords: "2nd second highest salary max subquery limit offset",
  },
  {
    title: "Find Duplicate Records",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#find-dup",
    keywords: "find duplicate records group by having count greater than 1",
  },
  {
    title: "Delete Duplicate Records",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#del-dup",
    keywords: "delete duplicate remove row_number cte partition keep one",
  },
  {
    title: "Highest Salary by Department",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#dept-salary",
    keywords: "department highest salary max group by top per category",
  },
  {
    title: "Employees Above Department Average",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#above-avg",
    keywords: "above average department salary subquery correlated group having",
  },
  {
    title: "Same Salary Employees",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#same-salary",
    keywords: "same salary employees self join group count pair",
  },
  {
    title: "Self Join — Manager Name",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#self-join",
    keywords: "self join manager employee hierarchy same table alias",
  },
  {
    title: "Department with 5+ Employees",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#having-count",
    keywords: "having count department employees filter group by",
  },
  {
    title: "Customers with No Orders",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#no-orders",
    keywords: "customers no orders left join null not in exists",
  },
  {
    title: "DELETE vs DROP vs TRUNCATE",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#del-drop-trunc",
    keywords: "delete drop truncate difference remove table data structure dml ddl",
  },
  {
    title: "WHERE vs HAVING",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#where-having",
    keywords: "where having difference filter row group aggregate before after",
  },
  {
    title: "INNER vs LEFT JOIN",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#joins",
    keywords: "inner left join match null unmatched all rows",
  },
  {
    title: "UNION vs UNION ALL",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#union",
    keywords: "union union all combine result set duplicate distinct",
  },
  {
    title: "Subquery vs Correlated Subquery",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#subquery",
    keywords: "subquery correlated nested inner query dependent outer row",
  },
  {
    title: "Normalization in SQL",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#normalization",
    keywords: "normalization 1nf 2nf 3nf normal form reduce redundancy anomaly",
  },
  {
    title: "PRIMARY vs FOREIGN Key in SQL",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#keys",
    keywords: "primary foreign key constraint unique referential integrity relationship",
  },
  {
    title: "Indexing in SQL",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#indexing",
    keywords: "index create drop performance query speed btree hash explain",
  },
  {
    title: "ACID Properties in SQL",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#acid",
    keywords: "acid atomicity consistency isolation durability transaction sql commit rollback",
  },
  {
    title: "Clustered vs Non-Clustered Index",
    topic: "SQL",
    chapter: "SQL",
    url: "09-SQL.html#clustered",
    keywords: "clustered non clustered index physical order logical sort",
  },

  // ──────────────── BEHAVIORAL ────────────────
  {
    title: "Projects & Behavioral Interview",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html",
    keywords: "projects behavioral star method leadership conflict ownership design tradeoff interview soft skills",
  },
  {
    title: "Project Architecture Discussion",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#architecture",
    keywords: "architecture design pattern microservice monolith system design scalability tradeoff decision",
  },
  {
    title: "Biggest Challenge Faced",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#challenge",
    keywords: "challenge obstacle problem solving difficult hard situation overcome learn",
  },
  {
    title: "Why This Tech Stack?",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#tech-stack",
    keywords: "tech stack choice technology reason decision tradeoff why react node python",
  },
  {
    title: "Scalability Discussion",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#scalability",
    keywords: "scalability scale horizontal vertical load million users growth bottleneck",
  },
  {
    title: "Database Design Discussion",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#database",
    keywords: "database design schema normalization er diagram table relation choice sql nosql",
  },
  {
    title: "Security Discussion",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#security",
    keywords: "security authentication authorization jwt oauth encryption csrf xss sql injection",
  },
  {
    title: "Performance Optimization",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#performance",
    keywords: "performance optimization speed caching lazy loading cdn query bundle metrics",
  },
  {
    title: "CI/CD Pipeline",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#cicd",
    keywords: "ci cd pipeline continuous integration deployment github actions jenkins docker automation test",
  },
  {
    title: "Monitoring & Logging",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#monitoring",
    keywords: "monitoring logging grafana prometheus elk alert dashboard observability metric",
  },
  {
    title: "Caching Strategy",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#caching",
    keywords: "caching strategy redis memcached lru ttl invalidation hit miss",
  },
  {
    title: "Failure Handling",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#failure",
    keywords: "failure handling error recovery fallback retry circuit breaker graceful degradation",
  },
  {
    title: "Team Conflict Resolution",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#conflict",
    keywords: "conflict resolution team disagreement communication compromise collaboration",
  },
  {
    title: "Leadership Example",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#leadership",
    keywords: "leadership lead initiative ownership mentor team responsibility",
  },
  {
    title: "Production Bug Story",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#bug",
    keywords: "production bug incident postmortem root cause fix debug hotfix",
  },
  {
    title: "Why Should We Hire You?",
    topic: "Behavioral",
    chapter: "Behavioral",
    url: "10-Projects-Behavioral.html#hire",
    keywords: "why hire you strength value fit passion growth contribution unique",
  },
  // ──────────────── SYSTEM DESIGN ────────────────
  {
    title: "System Design — Scalability & Architecture",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html",
    keywords: "system design interview scalability architecture load balancer caching sharding microservices API design message queue CDN rate limiting real-time",
  },
  {
    title: "Scalability — Scale Up vs Scale Out",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#scalability",
    keywords: "scalability vertical horizontal scale up scale out server auto scaling",
  },
  {
    title: "Load Balancer — Traffic Distribution",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#load-balancer",
    keywords: "load balancer round robin least connections ip hash nginx haproxy AWS ALB health check",
  },
  {
    title: "Caching — Redis, Memcached Strategies",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#caching",
    keywords: "cache redis memcached TTL cache-aside write-through write-behind invalidation stampede",
  },
  {
    title: "Database Scaling — Sharding & Replication",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#db-scaling",
    keywords: "database sharding replication primary replica consistent hashing federation vertical partitioning",
  },
  {
    title: "Consistent Hashing",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#consistent-hashing",
    keywords: "consistent hashing ring virtual nodes vnodes dynamodb cassandra distribution",
  },
  {
    title: "Message Queues — Kafka, RabbitMQ",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#message-queues",
    keywords: "message queue kafka rabbitmq async producer consumer pub sub event streaming",
  },
  {
    title: "Microservices vs Monolith",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#microservices",
    keywords: "microservices monolith API gateway service discovery saga pattern strangler fig",
  },
  {
    title: "API Design — REST Best Practices",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#api-design",
    keywords: "API REST design GET POST PUT PATCH DELETE pagination versioning rate limiting idempotency",
  },
  {
    title: "CDN — Content Delivery Network",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#cdn",
    keywords: "CDN content delivery edge cloudflare cloudfront akamai cache busting edge computing",
  },
  {
    title: "Design a URL Shortener (System Design)",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#url-shortener",
    keywords: "URL shortener bitly system design base62 encoding redirect analytics",
  },
  {
    title: "Rate Limiting & Throttling",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#rate-limiting",
    keywords: "rate limiting token bucket sliding window fixed window throttling 429 stripe",
  },
  {
    title: "Real-Time Systems & WebSockets",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#realtime",
    keywords: "websocket real time SSE server sent events polling long polling socket.io chat gaming",
  },
  {
    title: "CAP Theorem in Practice",
    topic: "System Design",
    chapter: "System Design",
    url: "11-System-Design.html#cap-deep",
    keywords: "CAP theorem consistency availability partition tolerance eventual consistency dynamodb cassandra PACELC",
  },

  // ──────────────── DSA CONCEPTS ────────────────
  {
    title: "DSA — Data Structures & Algorithm Concepts",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html",
    keywords: "DSA data structures algorithms interview big O complexity array linked list tree graph hash table sorting dynamic programming",
  },
  {
    title: "Time & Space Complexity (Big-O)",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#complexity",
    keywords: "big O time complexity space complexity O(1) O(log n) O(n) O(n log n) O(n^2) amortized master theorem",
  },
  {
    title: "Arrays & Strings",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#arrays-strings",
    keywords: "array string two pointer sliding window prefix sum anagram substring palindrome rotation",
  },
  {
    title: "Linked Lists",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#linked-lists",
    keywords: "linked list singly doubly reverse cycle detection floyd merge middle palindrome dummy head",
  },
  {
    title: "Stacks & Queues",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#stacks-queues",
    keywords: "stack queue LIFO FIFO monotonic stack deque BFS balanced parentheses implement",
  },
  {
    title: "Hash Tables / HashMaps",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#hash-tables",
    keywords: "hash table hashmap dictionary collision chaining open addressing load factor rehash",
  },
  {
    title: "Trees & Binary Search Trees",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#trees",
    keywords: "binary tree BST traversal inorder preorder postorder BFS DFS LCA diameter height balanced AVL",
  },
  {
    title: "Graphs — BFS, DFS, Dijkstra",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#graphs",
    keywords: "graph BFS DFS adjacency list matrix dijkstra topological sort cycle detection connected components island",
  },
  {
    title: "Sorting Algorithms",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#sorting",
    keywords: "merge sort quicksort heap sort counting sort stable sorting tim sort quickselect partition",
  },
  {
    title: "Binary Search",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#binary-search",
    keywords: "binary search rotated sorted array lower bound upper bound search answer monotonic",
  },
  {
    title: "Dynamic Programming",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#dp",
    keywords: "dynamic programming DP memoization tabulation fibonacci knapsack LCS coin change climbing stairs edit distance",
  },
  {
    title: "Recursion & Backtracking",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#recursion",
    keywords: "recursion backtracking permutations combinations N-Queens sudoku word search base case",
  },
  {
    title: "Greedy Algorithms",
    topic: "DSA",
    chapter: "DSA",
    url: "12-DSA-Concepts.html#greedy",
    keywords: "greedy algorithm activity selection huffman fractional knapsack optimal exchange argument",
  },

  // ──────────────── QUIZ PAGES ────────────────
  {
    title: "DBMS Quiz",
    topic: "Quiz",
    chapter: "DBMS",
    url: "Quiz/01-DBMS.html",
    keywords: "dbms quiz database quiz interview practice test questions",
  },
  {
    title: "OOPs Quiz",
    topic: "Quiz",
    chapter: "OOPs",
    url: "Quiz/02-OOPs.html",
    keywords: "oops quiz object oriented quiz interview practice test questions",
  },
  {
    title: "Computer Networks Quiz",
    topic: "Quiz",
    chapter: "Networks",
    url: "Quiz/03-Computer-Networks.html",
    keywords: "networks quiz computer networks quiz interview practice test questions",
  },
  {
    title: "Operating System Quiz",
    topic: "Quiz",
    chapter: "OS",
    url: "Quiz/04-Operating-System.html",
    keywords: "os quiz operating system quiz interview practice test questions",
  },
  {
    title: "C++ Core Quiz",
    topic: "Quiz",
    chapter: "C++",
    url: "Quiz/05-Language-Core-CPP.html",
    keywords: "cpp quiz c++ quiz language core quiz interview practice test questions",
  },
  {
    title: "Java Core Quiz",
    topic: "Quiz",
    chapter: "Java",
    url: "Quiz/05-Language-Core-Java.html",
    keywords: "java quiz language core quiz interview practice test questions",
  },
  {
    title: "Python Core Quiz",
    topic: "Quiz",
    chapter: "Python",
    url: "Quiz/05-Language-Core-Python.html",
    keywords: "python quiz language core quiz interview practice test questions",
  },
  {
    title: "Puzzles Quiz",
    topic: "Quiz",
    chapter: "Puzzles",
    url: "Quiz/06-Puzzles.html",
    keywords: "puzzles quiz brain teasers quiz interview practice test questions",
  },
  {
    title: "Linux Quiz",
    topic: "Quiz",
    chapter: "Linux",
    url: "Quiz/07-Linux.html",
    keywords: "linux quiz system admin quiz interview practice test questions",
  },
  {
    title: "Git Quiz",
    topic: "Quiz",
    chapter: "Git",
    url: "Quiz/08-Git.html",
    keywords: "git quiz version control quiz interview practice test questions",
  },
  {
    title: "SQL Quiz",
    topic: "Quiz",
    chapter: "SQL",
    url: "Quiz/09-SQL.html",
    keywords: "sql quiz query language quiz interview practice test questions",
  },
  {
    title: "Projects & Behavioral Quiz",
    topic: "Quiz",
    chapter: "Behavioral",
    url: "Quiz/10-Projects-Behavioral.html",
    keywords: "behavioral quiz projects quiz soft skills quiz interview practice test questions",
  },

];
